@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include FONTAWESOME/users.puml

SHOW_PERSON_OUTLINE()
left to right direction

Person(BTEAlias, "Test Engineer", "A Board\nTest Engineer")
Person(FPGADes, "FPGA Designer", "An FPGA Designer")

System_Boundary(BrdPTPG, "Board Level PTPG", "Takes CAD data, device model, and data to generate reusable native programming/configuration objectives"){
    System(Vivado, "Xilinx Vivado - FPGA Development Tool", "Vivado IP Integrator provides a graphical and Tcl-based, correct-by-construction design development flow. Working at the interface level, design teams can rapidly assemble complex systems that leverage IP")
    System(Quartus, "Intel Quartus Prime", "Software that can easily adapt to your specific needs in all phases of FPGA, CPLD, and SoC design in different platforms")
    System(Lattice, "Lattice Diamond", "Leading-edge design and implementation tools optimized for Lattice low-power FPGA architectures")
    System(FlashPrgm, "FLASH Programmer", "A tool to program the contents of a FLASH memory device via JTAG bit-bang, I2C, SPI, or device emulation interfaces")
    System(EEPROMPrgm, "EEPROM Programmer","A tool to program the contents of an EEPROM memory device via JTAG bit-bang, I2C, SPI, or device emulation interfaces.")
    System(DSLApp, "Domain Specific Language (DSL) Application", "An application to execute procedures written in a DSL for a specific domain to perform operations on the BUT")
    ContainerDb(LocalStore, "Local Repository", "Test Deployment", "Storage for JTAG native tests")
}
ContainerDb_Ext(BCADRepo, "Board CAD Repository", "Tooling", "Persistent storage of CAD information")
SystemDb_Ext(BDbDataAlias, "Board Programming Repository", "A repository of software, firmware, and configuration data for a board")
SystemDb_Ext(BDbAlias, "Board Test Repository", "A repository where tests are preserved for production")
SystemDb_Ext(BDbMemAlias, "Board Memory Model Repository", "A repository of memory access algorithms for memory devices")
SystemDb_Ext(BDbDSLAlias, "Board DSL Procedure Repository", "A repository of DSL procedures written by testers of the BUT")

Rel(FPGADes, Vivado, "FPGA Design", "Design")
Rel(FPGADes, Quartus, "FPGA Design", "Design")
Rel(FPGADes, Lattice, "FPGA Design", "Design")
Rel(BTEAlias, Vivado, "Program Generation", "Test Development")
Rel(BTEAlias, Quartus, "Program Generation", "Test Development")
Rel(BTEAlias, Lattice, "Program Generation", "Test Development")
Rel(BTEAlias, FlashPrgm, "Program Generation", "Test Development")
Rel(BTEAlias, EEPROMPrgm, "Program Generation", "Test Development")
Rel(BTEAlias, DSLApp, "Program Generation", "Test Development")
Rel_D(Vivado, LocalStore, "Stores", "Test Deployment")
Rel_D(Quartus, LocalStore, "Stores", "Test Deployment")
Rel_D(Lattice, LocalStore, "Stores", "Test Deployment")
Rel_D(FlashPrgm, LocalStore, "Stores", "Test Deployment")
Rel_D(EEPROMPrgm, LocalStore, "Stores", "Test Deployment")
Rel_D(DSLApp, LocalStore, "Stores", "Test Deployment")
Rel_U(BCADRepo, LocalStore, "Provides CAD data for tool automation", "Test Development")
Rel(LocalStore, DSLApp, "CAD Data", "Test Development")
Rel_U(BDbAlias, LocalStore, "Provides Tests", "Test Deployment")
Rel_U(LocalStore, Vivado, "Provides Content", "Test Deployment")
Rel_U(LocalStore, Quartus, "Provides Content", "Test Deployment")
Rel_U(LocalStore, Lattice, "Provides Content", "Test Deployment")
Rel_U(LocalStore, FlashPrgm, "Provides Content", "Test Deployment")
Rel_U(LocalStore, EEPROMPrgm, "Provides Content", "Test Deployment")
Rel_U(LocalStore, DSLApp, "Provides Content", "Test Deployment")
Rel(LocalStore, BDbAlias, "Test Steps", "Test Development")
Rel(BDbMemAlias, FlashPrgm, "Provides algorithms", "Test Generation")
Rel(BDbMemAlias, EEPROMPrgm, "Provides algorithms", "Test Generation")
Rel(BDbDSLAlias, DSLApp, "Provides", "Test Generation")
Rel(BDbDataAlias, Vivado, "Provides Content", "Test Generation")
Rel(BDbDataAlias, Quartus, "Provides Content", "Test Generation")
Rel(BDbDataAlias, Lattice, "Provides Content", "Test Generation")
Rel(BDbDataAlias, FlashPrgm, "Provides Content", "Test Generation")
Rel(BDbDataAlias, EEPROMPrgm, "Provides Content", "Test Generation")
Rel(BDbDataAlias, DSLApp, "Provides Content", "Test Generation")
@enduml
