@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include FONTAWESOME/users.puml

SHOW_PERSON_OUTLINE()
left to right direction

Person(DTEAlias, "Test Engineer", "A Device\nTest Engineer")
Person(SWDevAlias, "SW Developer", "A Software Developer responsible for developing or integrating instrumentation PDL procedures and scripts")
Person(DDESAlias, "Designer", "ASIC/FPGA Designer")
Person(SchemLayoutExpert, "Specialist", "Schematic Layout Expert")

System_Boundary(DEDAAlias, "Device EDA Tooling", "A set of tools to design, generate firmware, and develop tests for devices."){
    System(DTest, "Device Level Test Generation", "Implements test/programming/configuration objectives")
    System(Synthesis, "Synthesis Tool", "Gate-level synthesis tool with formal verification and scan insertion")
    System(PlaceAndRoute, "Place & Route Tool", "The gate-level netlist from the synthesis tool is taken and imported into place and route tool in Verilog netlist format. All the gates and flip-flops are placed; clock tree synthesis and reset is routed. After this each block is routed.")
    ContainerDb(DCADRepo, "Device CAD Repository", "Tooling", "Persistent storage of CAD information")
    ContainerDb(LocalRepo, "Device Local Repository", "Storage", "Local persistent storage")
}
System_Ext(DevTest, "Device Test Equipment", "An automated system for applying tests through a fixture to a DUT to perform test, validation, and diagnosis")
SystemDb_Ext(DevDbAlias, "Device Test Repository", "A repository where tests are preserved for production")

Rel(DDESAlias, Synthesis, "Creates gate-level implementation for target technology", "Design")
Rel(DDESAlias, PlaceAndRoute, "Creates initial layout", "Design")
Rel(SchemLayoutExpert, PlaceAndRoute, "Refines layout", "Design")

Rel(SWDevAlias, DTest, "Device Test Generation", "Test Development")
Rel(DTEAlias, DTest, "Device Test Generation", "Test Development")
Rel(DTEAlias, DevTest, "Produces Tests For", "Test Deployment")
Rel(DTest, DevTest, "Produces Tests For", "Test Deployment")
Rel(DTest, LocalRepo,"Preserves tests", "Test Deployment")
Rel(LocalRepo, DevDbAlias,"Preserves tests", "Test Deployment")
Rel(DevDbAlias, DevTest, "Reuse of tests", "Test Deployment")
Rel(DevDbAlias, LocalRepo, "Provides Device Tests", "Design, Production")
Rel(LocalRepo, DTest, "Provides Device Tests", "Design, Production")
Rel(DevTest, DevDbAlias, "Stores native tests", "Test Deployment")
Rel(DevDbAlias, LocalRepo, "Provides Test Benches", "Design")
Rel(LocalRepo, DevDbAlias, "Stores Test Bench Results", "Design")
Rel(DCADRepo, DTest, "Provides CAD data for tool automation", "Test Development")
@enduml
