@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include FONTAWESOME/users.puml

SHOW_PERSON_OUTLINE()

Person(DTEAlias, "Test Engineer", "A Device\nTest Engineer")
Person(DTOAlias, "Test Operator", "A Device\nTest Operator")

System_Ext(DUTAlias, "Device Under Test", "A device that contains IEEE 1687 instrumentation")
System_Ext(EDAAlias, "Device EDA Tooling", "A set of tools to design, generate RTL, and develop tests for IP and devices.")
System_Boundary(ATEAlias, "Device Automated Test Equipment (ATE)", "An automated system for applying tests through a fixture to a DUT to perform test, validation, and diagnosis"){
    System(ATEGen, "Test Generator for ATE", "Takes STIL and other test formats and generates native test programs")
    System(ATETester, "ATE Test System", "Takes native tests and applies them to DUT")
    ContainerDb(ATEStore, "ATE Local Repository", "Test Deployment", "Storage for ATE native tests")
}
SystemDb_Ext(DevDbAlias, "Device Test Repository", "A repository where tests are preserved for production")

Rel(DTEAlias, EDAAlias, "ATPG Generation", "Test Development")
Rel_R(DTEAlias, DUTAlias, "Test Generation", "Test Application")
Rel_D(DTEAlias, ATEGen, "Produces Tests For", "Test Deployment")
Rel_R(EDAAlias, ATEGen, "Produces Tests For", "Test Deployment")
Rel_U(DTOAlias, ATETester, "Volume Testing Devices", "Mfg Test")
Rel_R(ATETester, DUTAlias, "Tests", "Mfg Test")
Rel(EDAAlias, DevDbAlias,"Preserves ATPG tests", "Test Deployment")
Rel_U(DevDbAlias, ATEGen, "Reuse of tests", "Test Deployment")
Rel(ATEGen, ATEStore, "Stores native tests", "Test Deployment")
Rel(ATEStore, ATETester, "Provides", "Test Deployment")
Rel_R(ATEStore, DevDbAlias, "Store native tests", "Test Deployment")
Rel(ATEGen, EDAAlias, "Provide data response for diagnostic analysis", "Test Analysis")
@enduml
