@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include FONTAWESOME/users.puml

SHOW_PERSON_OUTLINE()
left to right direction

Person(STEAlias, "Test Engineer", "A System\nTest Engineer")
Person(SWDevAlias, "SW Developer", "A Software Developer responsible for in-system testing and/or operation")

System_Boundary(SysEmbed, "Embedded System Test Environment", "The OA&M portion of the application used to configure, test, and operate the systems"){
    System(IDE, "Integrated Development Environment (IDE for C, C++, C#, Java, Python, Tcl, etc.)","A development environment for creating test and measurement applications for embedded and adjunct environments")
    System(CustomTools, "Custom Tooling","A suite of in-house tooling to support product development")
    ContainerDb(LocalStore, "Local Repository", "Test Deployment", "Storage for native tests")
}
ContainerDb_Ext(SCADRepo, "System CAD Repository", "Tooling", "Persistent storage of CAD information")
SystemDb_Ext(BDbAlias, "Board Test Repository", "A repository where tests are preserved for production")
SystemDb_Ext(SDbAlias, "System Test Repository", "A repository where tests are preserved for production")
SystemDb_Ext(ConstraintModelAlias, "Constraints Model Repository", "Definitions of constraints of signals required for tests run in-system environments")

Rel(STEAlias, IDE, "Embedded Test Generation", "Test Development")
Rel_D(IDE, LocalStore, "Stores Tests", "Test Deployment")
Rel_U(SCADRepo, LocalStore, "Provides CAD data for tool automation", "Test Development")
Rel(LocalStore, SDbAlias, "Test Steps", "Test Development")
Rel(ConstraintModelAlias, CustomTools,  "Provides", "Test Generation")
Rel_U(BDbAlias, LocalStore, "Provides Tests", "Test Deployment")
Rel_U(SDbAlias, LocalStore, "Provides Tests", "Test Deployment")
Rel_U(LocalStore, IDE, "Provides Tests", "Test Deployment")
Rel_U(LocalStore, CustomTools, "Provides CAD data for tool automation", "Test Development")
Rel_U(LocalStore, CustomTools, "Provides Tests", "Test Deployment")
Rel_D(CustomTools, LocalStore, "Stores Tests", "Test Deployment")
Rel_D(SWDevAlias, IDE, "Integrates embedded tests for Systems", "In-System Test")
Rel_D(SWDevAlias, CustomTools, "Develops custom tools and tests for Systems", "In-System Test")
@enduml
